// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0xlFRcktoZZjXGvZU70y9RruPoL-FUQ',
    appId: '1:367248746262:web:b502aa4fa576837d47d237',
    messagingSenderId: '367248746262',
    projectId: 'tezis-abf56',
    authDomain: 'tezis-abf56.firebaseapp.com',
    storageBucket: 'tezis-abf56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArfeRT7AUCxTVzrTGAhzd5cm90IBXN7k',
    appId: '1:367248746262:android:f2b6b768bc4e1bcb47d237',
    messagingSenderId: '367248746262',
    projectId: 'tezis-abf56',
    storageBucket: 'tezis-abf56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHsMYTTNKL2Ej-pNPpDcw82ZNMiv4q1gA',
    appId: '1:367248746262:ios:ff51ab648692f9a047d237',
    messagingSenderId: '367248746262',
    projectId: 'tezis-abf56',
    storageBucket: 'tezis-abf56.appspot.com',
    iosBundleId: 'com.example.tesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHsMYTTNKL2Ej-pNPpDcw82ZNMiv4q1gA',
    appId: '1:367248746262:ios:e982c25a1eebb7e847d237',
    messagingSenderId: '367248746262',
    projectId: 'tezis-abf56',
    storageBucket: 'tezis-abf56.appspot.com',
    iosBundleId: 'com.example.tesis.RunnerTests',
  );
}
